name: education
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.5
  provider: ^6.0.1
  gradient_coloured_buttons: ^0.1.0
  neon_widgets: ^2.0.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  analyzer: ^4.7.0


flutter:
  uses-material-design: true
