name: Dependencies

on:
  push:
    branches:
      - lab7
  pull_request:
    branches:
      - lab7

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test

      - run: flutter build web --release

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web